Clean up install logging

diff --git a/setup/install b/setup/install
--- a/setup/install
+++ b/setup/install
@@ -7,6 +7,9 @@ dotfiles_root="$(pwd -P)"
 home_dotfiles="${HOME}/.dotfiles"
 workspace="${HOME}/workspace"
 
+log="${HOME}/dotfile_install.log"
+> log
+
 info () {
 	printf "\r	[ \033[00;34m..\033[0m ] $1\n"
 }
@@ -34,9 +37,13 @@ install_workspace () {
 		"${workspace}/volume" \
 		"${HOME}/.vim/tmp/backupdir" \
 		"${HOME}/.vim/tmp/swpdir" \
-		"${HOME}/.vim/tmp/undodir" \
+		"${HOME}/.vim/tmp/undodir" 1>> $log 2>&1
 
-	success "installed workspace"
+	if [ $? == 0]; then
+		success "installed workspace"
+	else
+		error "could not install workspace, check $log"
+	fi
 }
 
 install_dotfiles () {
@@ -47,18 +54,33 @@ install_dotfiles () {
 		--include="*/" \
 		--exclude=".git" \
 		--exclude="*" \
-		"${dotfiles_root}/" "${home_dotfiles}"
+		"${dotfiles_root}/" "${home_dotfiles}" 1>> $log 2>&1
 
-	success "installed dotfiles"
+	if [ $? == 0]; then
+		success "installed dotfiles"
+	else
+		error "could not install dotfiles, check $log"
+	fi
 }
 
 get_theme () {
-	mkdir -vp "${home_dotfiles}/themes"
+	local ret
+	ret=0
 
-	curl --url "https://raw.githubusercontent.com/subtlepseudonym/loki-theme/master/themes/loki.zsh-theme" -o "${home_dotfiles}/themes/loki.zsh-theme"
-	curl --url "https://raw.githubusercontent.com/subtlepseudonym/loki-theme/master/git-patch.zsh" -o "${home_dotfiles}/zsh/git-patch.zsh"
+	mkdir -vp "${home_dotfiles}/themes" 1>> $log 2>&1
+	ret=$(( $ret | $? ))
 
-	success "installed theme"
+	curl --url "https://raw.githubusercontent.com/subtlepseudonym/loki-theme/master/themes/loki.zsh-theme" -o "${home_dotfiles}/themes/loki.zsh-theme" 1>> $log 2>&1
+	ret=$(( $ret | $? ))
+
+	curl --url "https://raw.githubusercontent.com/subtlepseudonym/loki-theme/master/git-patch.zsh" -o "${home_dotfiles}/zsh/git-patch.zsh" 1>> $log 2>&1
+	ret=$(( $ret | $? ))
+
+	if [ $? == 0]; then
+		success "installed theme"
+	else
+		error "could not install theme, check $log"
+	fi
 }
 
 link_file () {
